 version: '3.3'

 services:
  demo1:
    container_name: demo1
    build: .
    image: demo1
    depends_on:
      - db
    ports:
    - "8005:8005"

  db:
   hostname: db
   image: postgres:13.4-alpine
   env_file:
    - ./database-db/database.env
   volumes:
    - ./database-db/db.sql:/docker-entrypoint-initdb.d/db.sql
    - ./database-db/db:/var/lib/postgresql/db/
   ports:
   - "5433:5432"