server:
  port: 8005
  servlet:
    context-path: /demo
spring:
  liquibase:
    change-log: db.changelog-master.xml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform:  org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://db:5432/tdb
    driver-class-name: org.postgresql.Driver
    username:  postgres
    password:  postgres

